services:
  klipper:
    image: ghcr.io/mkocot/klipper-web-control-docker:ender3-klipper
    #build:
    #  dockerfile: ./klipper/Dockerfile
    #  context: .
    #  # args:
    #  #   DEVICE_GROUP: device
    #  #   DEVICE_GID: 987
    # if klipper cannot connect to the printer check permissions on rpi then add the group here
    # group_add:
    #   - "996"
    #   - "998"
    container_name: klipper
    privileged: true
    restart: unless-stopped
    volumes:
      - moonraker_data:/home/klippy/printer_data
      - moonraker_logs_tmpfs:/home/klippy/printer_data/logs
      - gcode_files:/home/klippy/printer_data/gcodes
      # be aware to create your own branch if you mount the config folder as it will be updated on the main branch
      # that way you can merge upstream changes to your customized configs
      - ./config:/home/klippy/printer_data/config
      # /dev is required for (dynamic) sharing printer and host serial
      - /dev:/dev
      # My own experimental plugin
      - ./gcode_pid.py:/home/klippy/klipper/klippy/extras/gcode_pid.py
    # mount serial device - take care to grant sufficient permissions to the device: <host_dev>:<container_dev>
    # put <container_dev> into your printer.cfg
    #devices:
    #  - /dev/ttyUSB0:/dev/ttyUSB0
  klipper_mcu:
    image: ghcr.io/mkocot/klipper-web-control-docker:ender3-klipper_mcu
    #user: root
    container_name: klipper_mcu
    privileged: true
    cap_add:
      - sys_nice
    restart: unless-stopped
    volumes_from:
      - klipper
    depends_on: 
      - klipper
  moonraker:
    image: ghcr.io/mkocot/klipper-web-control-docker:ender3-moonraker
    container_name: moonraker
    privileged: false
    ports:
      - 7125:7125
    restart: unless-stopped
    volumes_from:
      - klipper
    volumes:
      # bind secrets file to printer_data on docker
      - ./config/moonraker.secrets:/home/klippy/printer_data/moonraker.secrets
    environment:
        # Disable saving logs from moonraker
        - 'MOONRAKER_DISABLE_FILE_LOG=True'
    depends_on: 
      - klipper
      - klipper_mcu


  fluidd:
    image: ghcr.io/fluidd-core/fluidd:latest
    restart: unless-stopped
    container_name: fluidd
    ports:
      - 8010:80
    depends_on: 
      - moonraker

  notifier:
    container_name: notifier
    restart: unless-stopped
    image: klipper-web-control-docker_notifier
    #build:
    #  dockerfile: extras/Dockerfile.matrix-webhook
    #  context: .
    #ports:
    #  - 4785:4785
    command: -u ${MATRIX_WEBHOOK_SERVER} -i ${MATRIX_WEBHOOK_USER} -p ${MATRIX_WEBHOOK_PASSWORD} -k ${MATRIX_WEBHOOK_API_KEY}

volumes: 
  gcode_files:
  gcode_files_tmpfs:
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: size=50m
  moonraker_data:
  moonraker_logs_tmpfs:
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: size=100m
